// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsvWCbFZdESH4NMQCQY23ZJ_mv-6BkpIQ',
    appId: '1:435119148789:web:d261a82d182379077e7fbc',
    messagingSenderId: '435119148789',
    projectId: 'verde-ensina',
    authDomain: 'verde-ensina.firebaseapp.com',
    storageBucket: 'verde-ensina.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuouB0KXdHzePWsfmnBHsvlmkIHzBqz-s',
    appId: '1:435119148789:android:74691578a4ef1c6f7e7fbc',
    messagingSenderId: '435119148789',
    projectId: 'verde-ensina',
    storageBucket: 'verde-ensina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWQa8us5b3YOXu1EDt1uKW8kECbGEtzow',
    appId: '1:435119148789:ios:f57f1b001a3a8e0c7e7fbc',
    messagingSenderId: '435119148789',
    projectId: 'verde-ensina',
    storageBucket: 'verde-ensina.firebasestorage.app',
    iosBundleId: 'com.example.verdeEnsina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWQa8us5b3YOXu1EDt1uKW8kECbGEtzow',
    appId: '1:435119148789:ios:f57f1b001a3a8e0c7e7fbc',
    messagingSenderId: '435119148789',
    projectId: 'verde-ensina',
    storageBucket: 'verde-ensina.firebasestorage.app',
    iosBundleId: 'com.example.verdeEnsina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsvWCbFZdESH4NMQCQY23ZJ_mv-6BkpIQ',
    appId: '1:435119148789:web:1cbf4a553c80cd7e7e7fbc',
    messagingSenderId: '435119148789',
    projectId: 'verde-ensina',
    authDomain: 'verde-ensina.firebaseapp.com',
    storageBucket: 'verde-ensina.firebasestorage.app',
  );
}
