// lib/canteiros/guia_culturas.dart

final Map<String, Map<String, dynamic>> guiaCompleto = {
  'Abobrinha italiana': {
    'cat': 'Frutos',
    'par': 'Milho, Feijão',
    'evitar': 'Batata',
    'ciclo': 55,
    'eLinha': 1.0,
    'ePlanta': 0.7,
  },
  'Abobrinha brasileira': {
    'cat': 'Frutos',
    'par': 'Milho, Feijão',
    'evitar': 'Batata',
    'ciclo': 60,
    'eLinha': 2.0,
    'ePlanta': 2.0,
  },
  'Abóboras e morangas': {
    'cat': 'Frutos',
    'par': 'Milho, Feijão',
    'evitar': 'Batata',
    'ciclo': 120,
    'eLinha': 3.0,
    'ePlanta': 2.0,
  },
  'Acelga': {
    'cat': 'Folhas',
    'par': 'Alface, Couve',
    'evitar': 'Nenhum',
    'ciclo': 60,
    'eLinha': 0.45,
    'ePlanta': 0.5,
  },
  'Agrião': {
    'cat': 'Folhas',
    'par': 'Nenhum',
    'evitar': 'Nenhum',
    'ciclo': 50,
    'eLinha': 0.2,
    'ePlanta': 0.3,
  },
  'Salsão (Aipo)': {
    'cat': 'Temperos',
    'par': 'Tomate, Feijão',
    'evitar': 'Milho',
    'ciclo': 100,
    'eLinha': 0.9,
    'ePlanta': 0.4,
  },
  'Alface': {
    'cat': 'Folhas',
    'par': 'Cenoura, Rabanete',
    'evitar': 'Salsa',
    'ciclo': 45,
    'eLinha': 0.25,
    'ePlanta': 0.3,
  },
  'Alho': {
    'cat': 'Bulbos',
    'par': 'Tomate, Cenoura',
    'evitar': 'Feijão',
    'ciclo': 180,
    'eLinha': 0.25,
    'ePlanta': 0.1,
  },
  'Alho poró': {
    'cat': 'Bulbos',
    'par': 'Cenoura, Tomate',
    'evitar': 'Feijão',
    'ciclo': 120,
    'eLinha': 0.4,
    'ePlanta': 0.2,
  },
  'Almeirão': {
    'cat': 'Folhas',
    'par': 'Alface, Cenoura',
    'evitar': 'Nenhum',
    'ciclo': 70,
    'eLinha': 0.25,
    'ePlanta': 0.25,
  },
  'Batata doce': {
    'cat': 'Raízes',
    'par': 'Abóbora',
    'evitar': 'Tomate',
    'ciclo': 120,
    'eLinha': 0.9,
    'ePlanta': 0.3,
  },
  'Berinjela': {
    'cat': 'Frutos',
    'par': 'Feijão, Alho',
    'evitar': 'Nenhum',
    'ciclo': 110,
    'eLinha': 1.0,
    'ePlanta': 0.8,
  },
  'Beterraba': {
    'cat': 'Raízes',
    'par': 'Cebola, Alface',
    'evitar': 'Milho',
    'ciclo': 70,
    'eLinha': 0.25,
    'ePlanta': 0.1,
  },
  'Brócolis': {
    'cat': 'Flores',
    'par': 'Beterraba, Cebola',
    'evitar': 'Morango',
    'ciclo': 100,
    'eLinha': 0.8,
    'ePlanta': 0.5,
  },
  'Cará (Inhame)': {
    'cat': 'Raízes',
    'par': 'Nenhum',
    'evitar': 'Nenhum',
    'ciclo': 240,
    'eLinha': 0.8,
    'ePlanta': 0.4,
  },
  'Cebola': {
    'cat': 'Bulbos',
    'par': 'Beterraba, Tomate',
    'evitar': 'Feijão',
    'ciclo': 140,
    'eLinha': 0.3,
    'ePlanta': 0.1,
  },
  'Cebolinha': {
    'cat': 'Temperos',
    'par': 'Cenoura, Morango',
    'evitar': 'Feijão',
    'ciclo': 60,
    'eLinha': 0.25,
    'ePlanta': 0.2,
  },
  'Cenoura': {
    'cat': 'Raízes',
    'par': 'Alface, Tomate',
    'evitar': 'Salsa',
    'ciclo': 100,
    'eLinha': 0.25,
    'ePlanta': 0.1,
  },
  'Chicória': {
    'cat': 'Folhas',
    'par': 'Alface, Rúcula',
    'evitar': 'Nenhum',
    'ciclo': 70,
    'eLinha': 0.3,
    'ePlanta': 0.3,
  },
  'Chuchu': {
    'cat': 'Frutos',
    'par': 'Abóbora, Milho',
    'evitar': 'Nenhum',
    'ciclo': 120,
    'eLinha': 5.0,
    'ePlanta': 5.0,
  },
  'Coentro': {
    'cat': 'Temperos',
    'par': 'Tomate',
    'evitar': 'Cenoura',
    'ciclo': 50,
    'eLinha': 0.2,
    'ePlanta': 0.2,
  },
  'Couve de folha': {
    'cat': 'Folhas',
    'par': 'Alecrim, Sálvia',
    'evitar': 'Morango, Tomate',
    'ciclo': 80,
    'eLinha': 0.8,
    'ePlanta': 0.5,
  },
  'Ervilha': {
    'cat': 'Leguminosas',
    'par': 'Cenoura, Milho',
    'evitar': 'Alho',
    'ciclo': 80,
    'eLinha': 1.0,
    'ePlanta': 0.5,
  },
  'Jiló': {
    'cat': 'Frutos',
    'par': 'Berinjela, Pimentão',
    'evitar': 'Nenhum',
    'ciclo': 100,
    'eLinha': 1.2,
    'ePlanta': 1.0,
  },
  'Mandioca': {
    'cat': 'Raízes',
    'par': 'Feijão, Milho',
    'evitar': 'Nenhum',
    'ciclo': 300,
    'eLinha': 3.0,
    'ePlanta': 2.0,
  },
  'Melancia': {
    'cat': 'Frutos',
    'par': 'Milho',
    'evitar': 'Nenhum',
    'ciclo': 90,
    'eLinha': 3.0,
    'ePlanta': 2.0,
  },
  'Melão': {
    'cat': 'Frutos',
    'par': 'Milho',
    'evitar': 'Nenhum',
    'ciclo': 90,
    'eLinha': 2.0,
    'ePlanta': 1.5,
  },
  'Morango': {
    'cat': 'Frutos',
    'par': 'Cebola, Alho',
    'evitar': 'Couve',
    'ciclo': 80,
    'eLinha': 0.35,
    'ePlanta': 0.35,
  },
  'Pepino': {
    'cat': 'Frutos',
    'par': 'Feijão, Milho',
    'evitar': 'Tomate',
    'ciclo': 60,
    'eLinha': 1.0,
    'ePlanta': 0.5,
  },
  'Pimenta': {
    'cat': 'Temperos',
    'par': 'Manjericão, Tomate',
    'evitar': 'Feijão',
    'ciclo': 100,
    'eLinha': 1.0,
    'ePlanta': 0.5,
  },
  'Pimentão': {
    'cat': 'Frutos',
    'par': 'Manjericão, Cebola',
    'evitar': 'Feijão',
    'ciclo': 100,
    'eLinha': 1.0,
    'ePlanta': 0.5,
  },
  'Quiabo': {
    'cat': 'Frutos',
    'par': 'Pimentão, Tomate',
    'evitar': 'Nenhum',
    'ciclo': 80,
    'eLinha': 1.0,
    'ePlanta': 0.3,
  },
  'Repolho': {
    'cat': 'Folhas',
    'par': 'Beterraba, Cebola',
    'evitar': 'Morango',
    'ciclo': 100,
    'eLinha': 0.8,
    'ePlanta': 0.4,
  },
  'Rúcula': {
    'cat': 'Folhas',
    'par': 'Alface, Beterraba',
    'evitar': 'Repolho',
    'ciclo': 40,
    'eLinha': 0.2,
    'ePlanta': 0.1,
  },
  'Tomate': {
    'cat': 'Frutos',
    'par': 'Manjericão, Alho',
    'evitar': 'Batata',
    'ciclo': 110,
    'eLinha': 1.0,
    'ePlanta': 0.3,
  },
};

final Map<String, Map<String, List<String>>> calendarioRegional = {
  'Sul': {
    'Fevereiro': [
      'Alface',
      'Beterraba',
      'Cebolinha',
      'Couve de folha',
      'Cenoura',
      'Tomate',
      'Pepino',
      'Repolho',
    ],
  },
  'Sudeste': {
    'Fevereiro': [
      'Alface',
      'Beterraba',
      'Berinjela',
      'Cebolinha',
      'Couve de folha',
      'Tomate',
      'Quiabo',
      'Pimentão',
    ],
  },
  'Nordeste': {
    'Fevereiro': [
      'Alface',
      'Berinjela',
      'Cenoura',
      'Quiabo',
      'Pepino',
      'Pimenta',
      'Tomate',
    ],
  },
  'Centro-Oeste': {
    'Fevereiro': [
      'Abobrinha italiana',
      'Abóboras e morangas',
      'Alface',
      'Almeirão',
      'Berinjela',
      'Cebola',
      'Brócolis',
      'Couve de folha',
    ],
  },
  'Norte': {
    'Fevereiro': [
      'Alface',
      'Batata doce',
      'Cenoura',
      'Quiabo',
      'Couve de folha',
      'Cebola',
    ],
  },
};
